name: musicplayer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  path: ^1.8.3
  path_provider: ^2.1.2
  audioplayers: ^1.1.1
  dio: ^5.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/musics/
  fonts:
    - family: FONT1
      fonts:
        - asset: assets/fonts/Noto_Serif,Protest_Revolution,Protest_Riot,Urbanist/Urbanist/Urbanist-Italic-VariableFont_wght.ttf
          weight: 700
        - asset: assets/fonts/Noto_Serif,Protest_Revolution,Protest_Riot,Urbanist/Noto_Serif/NotoSerif-VariableFont_wdth,wght.ttf
          weight: 700
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
